import React,{useState,useEffect} from 'react';
import {Sparkles,LoaderCircle,ExternalLink,X,Undo2} from 'lucide-react';
import {useLanguage} from './i18n.js';
function LibraryComparison({reasons=[],tr}) {
 return <div className="discover-comparison">
  <h4>{tr('Similar to games you play','Ähnlich wie deine Spiele')}</h4>
  {reasons.length ? <ul>{reasons.map((game,index)=>{
   const percent=typeof game.affinity==='number'&&Number.isFinite(game.affinity)&&game.affinity>=0&&game.affinity<=1?Math.round(game.affinity*100):null;
   return <li key={game.appid||index}>
    <strong>{game.name}</strong>
    {percent!==null&&<><span className="discover-similarity">{percent}% {tr('tag similarity','Tag-Ähnlichkeit')}</span><div className="discover-similarity-bar" aria-hidden="true"><span style={{width:`${percent}%`}}/></div></>}
   </li>;
  })}</ul>:<p>{tr('No individual comparison available.','Kein einzelner Vergleich verfügbar.')}</p>}
  <details><summary>{tr('What does this mean?','Was bedeutet das?')}</summary><p>{tr('Each percentage compares this suggestion’s Steam tags with one of your played games. Rarer tags carry more weight; 100% means identical tag profiles. These are separate comparisons, not genre shares or a prediction of how much you will enjoy a game. Your playtime influences the overall recommendation, not these percentages.','Jeder Prozentwert vergleicht die Steam-Tags dieses Vorschlags mit einem deiner gespielten Titel. Seltenere Tags zählen stärker; 100% bedeutet identische Tag-Profile. Die Vergleiche sind unabhängig voneinander – keine Genre-Anteile oder Vorhersage deines Spielspaßes. Deine Spielzeit beeinflusst die Gesamtempfehlung, nicht diese Prozentwerte.')}</p></details>
 </div>;
}
export default function Discover({request,active,blocked}){
 const language=useLanguage(),tr=(en,de)=>language==='de'?de:en;
 const [job,setJob]=useState({status:'idle',games:[]}),[pending,setPending]=useState(false),[error,setError]=useState(''),[excluded,setExcluded]=useState([]),[hidden,setHidden]=useState([]),[loaded,setLoaded]=useState(false);
 const [playMode,setPlayMode]=useState('all');
 const busy=pending||job.status==='running';
 useEffect(()=>{if(!active||loaded)return;let alive=true;Promise.all([request('/api/discover'),request('/api/discover/exclusions'),request('/api/discover/hidden')]).then(([j,e,h])=>{if(alive){setJob(j);setExcluded(e.games);setHidden(h.games);setLoaded(true);}}).catch(e=>{if(alive)setError(e.message);});return()=>{alive=false;};},[active,loaded]);
 useEffect(()=>{if(job.status!=='running')return;const timer=setInterval(()=>request('/api/discover').then(setJob).catch(e=>{setError(e.message);setJob(j=>({...j,status:'error'}));}),5000);return()=>clearInterval(timer);},[job.status]);
 const start=async()=>{if(busy||blocked)return;setPending(true);setError('');try{setJob(await request('/api/discover',{}));}catch(e){setError(e.message);}finally{setPending(false);}};
 const exclude=async(game,remove=false)=>{setPending(true);try{await request('/api/discover/exclusions',{appid:game.appid,remove});setExcluded((await request('/api/discover/exclusions')).games);setJob({status:'idle',games:[]});}catch(e){setError(e.message);}finally{setPending(false);}};
 const dismiss=async(game,remove=false)=>{setPending(true);try{await request('/api/discover/hidden',{appid:game.appid,remove});setHidden((await request('/api/discover/hidden')).games);}catch(e){setError(e.message);}finally{setPending(false);}};
 const games=(job.games||[]).filter(game=>!hidden.some(h=>h.appid===game.appid)).filter(game=>{
  const categories=game.categories||[];
  return playMode==='all'||(playMode==='online'?categories.includes(38):categories.some(id=>[9,38,39].includes(id)));
 });
 return <section id="discover" className="hub-section discover-section" hidden={!active}><div className="section-heading"><div><h2><Sparkles size={23}/> {tr('Find your next favourite','Finde deinen nächsten Favoriten')}</h2><p>{tr('New games you do not own, matched to the games you actually play.','Neue Spiele, die du noch nicht besitzt – passend zu deinen tatsächlich gespielten Titeln.')}</p></div><button className="button primary" disabled={busy||blocked} onClick={start}>{tr('Find my matches','Passende Spiele finden')}</button></div>
 {blocked&&<p role="status">{tr('Your library is updating. Matches will be available afterwards.','Deine Bibliothek wird aktualisiert. Danach kannst du Empfehlungen suchen.')}</p>}
 <p className="cache-note">{tr('Recommendations from a selection of up to 200 current Steam games. Open your taste profile below to see how matching works.','Empfehlungen aus einer Auswahl von bis zu 200 aktuellen Steam-Spielen. Öffne unten dein Geschmacksprofil, um die Berechnung nachzuvollziehen.')}</p>
 <div className="discover-filters"><label htmlFor="discover-play-mode">{tr('Play together','Zusammen spielen')}</label><select id="discover-play-mode" value={playMode} onChange={event=>setPlayMode(event.target.value)}><option value="all">{tr('All games','Alle Spiele')}</option><option value="coop">{tr('Co-op only','Nur Koop')}</option><option value="online">{tr('Online co-op only','Nur Online-Koop')}</option></select><span role="status">{tr(`${games.length} matches`,`${games.length} Treffer`)}</span></div>
 {playMode!=='all'&&<p className="cache-note">{tr('Filters your recommendations by Steam’s co-op features. Your taste ranking and library comparisons stay the same. “Co-op only” also includes local co-op.','Filtert deine Empfehlungen nach den Koop-Funktionen auf Steam. Deine Geschmackswertung und Bibliotheksvergleiche bleiben erhalten. „Nur Koop“ schließt auch lokalen Koop ein.')}</p>}
 {(error||job.error)&&<p role="alert" className="notice error">{error||job.error}</p>}
 <div className="discover-results" aria-busy={busy}>{busy&&<div className="coop-loading" role="status"><div className="coop-loading-card"><LoaderCircle className="loading"/><h3>{tr('Finding your matches','Wir suchen passende Spiele')}</h3><p>{job.total?`${job.done} / ${job.total}`:tr('Building your taste profile …','Dein Geschmacksprofil wird erstellt …')}</p><small>{tr('The first comparison can take a few minutes. Cached data is reused.','Die erste Auswertung kann einige Minuten dauern. Bekannte Daten werden wiederverwendet.')}</small></div></div>}
 <div className="game-grid">{games.slice(0,12).map(game=><article className="game-card" key={game.appid}><div className="game-cover">{game.image&&<img src={game.image} alt="" loading="lazy"/>}</div><div className="game-body"><h3>{game.name||`Steam game ${game.appid}`}</h3><span className="event-badge major">{game.match>=65?tr('Strong match','Starke Übereinstimmung'):tr('Similar interests','Ähnliche Interessen')}</span><LibraryComparison reasons={game.reasons} tr={tr}/><div className="card-bottom"><a href={`https://store.steampowered.com/app/${game.appid}/`} target="_blank" rel="noreferrer">{tr('View on Steam','Auf Steam ansehen')} <ExternalLink size={14}/></a><button disabled={busy} onClick={()=>dismiss(game)}><X size={14}/>{tr('Not interested','Kein Interesse')}</button></div></div></article>)}</div>
 {!games.length&&!busy&&<div className="empty"><Sparkles/><h3>{job.status==='complete'?(playMode!=='all'?tr('No co-op matches in these recommendations','Keine Koop-Treffer in diesen Empfehlungen'):tr('No strong matches in this catalogue','Keine starken Treffer in diesem Katalog')):tr('Your next discovery starts here','Hier beginnt deine nächste Entdeckung')}</h3><p>{playMode!=='all'&&job.status==='complete'?tr('Try All games or adjust your taste profile. Only confirmed Steam co-op features count; multiplayer alone is not enough.','Wähle Alle Spiele oder passe dein Geschmacksprofil an. Es zählen nur bestätigte Steam-Koop-Funktionen; Multiplayer allein reicht nicht.'):tr('Use your played games to find new ones. Playtime indicates interest, not a guaranteed favourite.','Nutze deine gespielten Titel, um neue zu entdecken. Spielzeit ist ein Indiz für Interesse, keine Garantie.')}</p>{playMode!=='all'&&<button className="button" onClick={()=>setPlayMode('all')}>{tr('Show all games','Alle Spiele anzeigen')}</button>}</div>}</div>
 {job.failed>0&&<p className="small-error">{tr('Some Steam details could not be checked: ','Einige Steam-Details konnten nicht geprüft werden: ')}{job.failed}</p>}
 <details className="coop-library"><summary>{tr('Your taste profile & hidden suggestions','Dein Geschmacksprofil & ausgeblendete Vorschläge')}</summary><p>{tr('The 16 most-played eligible games contribute log(1 + hours), with rarer tags weighted more strongly. Exclude idle-time outliers or games you did not enjoy. Exclusions and hidden suggestions expire after seven days.','Die 16 meistgespielten geeigneten Titel zählen mit log(1 + Stunden); seltenere Tags wiegen stärker. Schließe Spiele mit Leerlaufzeit oder ohne Spielspaß aus. Ausschlüsse und ausgeblendete Vorschläge verfallen nach sieben Tagen.')}</p>{(job.profile||[]).map(g=><div className="coop-library-row" key={g.appid}><span>{g.name} · {g.hours} h {!g.usable&&tr('(no tag data)','(keine Tags)')}</span><button disabled={busy||blocked} onClick={()=>exclude(g)}>{tr('Exclude','Ausschließen')}</button></div>)}{excluded.map(g=><div className="coop-library-row" key={g.appid}><span>{g.name}</span><button disabled={busy||blocked} onClick={()=>exclude(g,true)}>{tr('Restore to profile','Im Profil wiederherstellen')}</button></div>)}{hidden.map(g=><div className="coop-library-row" key={g.appid}><span>{g.name}</span><button disabled={busy} onClick={()=>dismiss(g,true)}><Undo2 size={14}/>{tr('Restore suggestion','Vorschlag wiederherstellen')}</button></div>)}</details></section>;
}
